=== smokedice/YATES/yates/config/validation/execution.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
 elementFormDefault="qualified"
 targetNamespace="exec"
 xmlns:exec = "exec">
  <xs:element name="execution">
    <xs:annotation>
      <xs:documentation>
        Most common set of parameters that could change between test suite executions
      </xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="exec:iterations" minOccurs="1" maxOccurs="1" />
        <xs:element ref="exec:defaultTimeout" minOccurs="1" maxOccurs="1" />
        <xs:element ref="exec:distributionAlgorithm" minOccurs="1" maxOccurs="1" />
        <xs:element name="rebootPerTest" type="xs:boolean" minOccurs="1" maxOccurs="1">
           <xs:annotation>
            <xs:documentation>If true, reboot the slave after each test</xs:documentation>
           </xs:annotation>
        </xs:element>
        <xs:element name="rebootNewBoxes" type="xs:boolean" minOccurs="1" maxOccurs="1">
           <xs:annotation>
            <xs:documentation>If true, reboot the slave when first discovered</xs:documentation>
           </xs:annotation>
        </xs:element>
        <xs:element name="manualInspection" type="xs:boolean" minOccurs="1" maxOccurs="1"/>
        <xs:element name="stopWhenAllDead" type="xs:boolean" minOccurs="1" maxOccurs="1">
           <xs:annotation>
            <xs:documentation>If true and all slaves are dead, stop the execution</xs:documentation>
           </xs:annotation>
        </xs:element>
        <xs:element ref="exec:scripts" minOccurs="1" maxOccurs="1" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="iterations">
   <xs:annotation>
    <xs:documentation>
        Iterate the test suite. A value of 0 equates to unlimited iterations
    </xs:documentation>
   </xs:annotation>
   <xs:simpleType>
    <xs:restriction base="xs:integer">
     <xs:minInclusive value="0" />
     <xs:maxInclusive value="100" />
    </xs:restriction>
   </xs:simpleType>
  </xs:element>
  <xs:element name="defaultTimeout">
    <xs:annotation>
      <xs:documentation>
            If a test does not detail a 'timeout' within it's docstring,
            this value is used
      </xs:documentation>
    </xs:annotation>
    <xs:simpleType >
        <xs:restriction base="xs:int">
            <xs:minInclusive value="5" />
        </xs:restriction>
    </xs:simpleType>
  </xs:element>
  <xs:element name="distributionAlgorithm">
    <xs:annotation>
      <xs:documentation>
            How to distribute the tests between the slaves. This is
            multiplied by the iterations to provide the number of 
            results expected.
            
            SingleExecution: Execute each test on a single box once
            ExecutionOnEachBox: Execute each test on each box
            ExecutionOnEachBoxEvenly: Execute each test on each box, but attempt to run a single instance of each test at a time
      </xs:documentation>
    </xs:annotation>
    <xs:simpleType>
      <xs:restriction base="xs:string">
        <xs:enumeration value="SingleExecution" />
        <xs:enumeration value="ExecutionOnEachBox" />
        <xs:enumeration value="ExecutionOnEachBoxEvenly" />
      </xs:restriction>
    </xs:simpleType>
  </xs:element>
  <xs:simpleType name="location">
     <xs:restriction base="xs:string">
        <xs:pattern value="(\.|[\.]{0,2}/[a-zA-Z0-9_\-/\.]+[^/]{1})$"></xs:pattern>
    </xs:restriction>
  </xs:simpleType>
  <xs:element name="scripts">
    <xs:annotation>
        <xs:documentation>
            Location where scripts are located for
            executing before, during and after execution.
            Value can be a relative or static path
            e.g ../tools, ./tools, /root/tools
        </xs:documentation>
    </xs:annotation>
    <xs:complexType>
        <xs:simpleContent>
            <xs:extension base="exec:location">
              <xs:attribute name="enabled" use="required" type="xs:boolean"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== smokedice/YATES/yates/config/execution.xml
<execution xmlns="exec"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="exec validation/execution.xsd">
    <iterations>1</iterations>
    <defaultTimeout>300</defaultTimeout>
    <distributionAlgorithm>ExecutionOnEachBoxEvenly</distributionAlgorithm>
    <rebootPerTest>false</rebootPerTest>
    <rebootNewBoxes>false</rebootNewBoxes>
    <manualInspection>false</manualInspection>
    <stopWhenAllDead>true</stopWhenAllDead>
    <scripts enabled="true">/tmp/tools</scripts>
</execution>
