=== smokedice/YATES/config/validation/discovery.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" 
 elementFormDefault="qualified"
 targetNamespace="discovery"
 xmlns:discovery = "discovery">
  <xs:element name="discovery" minOccurs="1" maxOccurs="1">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="discovery:PythonNose" minOccurs="0" maxOccurs="10" />
        <xs:element ref="discovery:StbTester" minOccurs="0" maxOccurs="10" />
      </xs:sequence>
    </xs:complexType>
    <xs:annotation>
        <xs:documentation>
            Configuration for discovering test cases from provided test suites
        </xs:documentation>
    </xs:annotation>
  </xs:element>
  <xs:element name="PythonNose">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="discovery:DiscoveryWorker" minOccurs="1" maxOccurs="1" />
        <xs:element ref="discovery:DatabaseReader" minOccurs="1" maxOccurs="1" />
        <xs:element ref="discovery:SourceLocation" minOccurs="1" maxOccurs="1" />
      </xs:sequence>
      <xs:attribute name="enabled" use="required" type="xs:boolean"/>
    </xs:complexType>
    <xs:annotation>
        <xs:documentation>
            Discovers tests from a database or a Python test suite.
            The enabled attribute disables the discovery of 
            PythonNose tests if they are not required within a test run.
        </xs:documentation>
    </xs:annotation>
  </xs:element>
  <xs:element name="StbTester">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="discovery:DiscoveryWorker" minOccurs="1" maxOccurs="1" />
        <xs:element ref="discovery:SourceLocation" minOccurs="1" maxOccurs="1" />
      </xs:sequence>
      <xs:attribute name="enabled" use="required" type="xs:boolean"/>
    </xs:complexType>
    <xs:annotation>
        <xs:documentation>
            Discovers tests from a StbTester test suite.
            The enabled attribute disalbes the discovery of StbTester
            tests if the are not required within a test run.
        </xs:documentation>
    </xs:annotation>
  </xs:element>
  <xs:element name="DiscoveryWorker">
    <xs:complexType>
      <xs:attribute name="enabled" use="required" type="xs:boolean"/>
    </xs:complexType>
    <xs:annotation>
        <xs:documentation>
            Discovers tests by reviewing the test suite provided.
            The filters configuration can be used to filter the 
            tests if not all tests are required. The enabled attribute can
            be used to disable the discovery of tests through the test files.
        </xs:documentation>
    </xs:annotation>
  </xs:element>
  <xs:element name="DatabaseReader">
    <xs:complexType>
        <xs:sequence>
            <xs:element name="location" minOccurs="0" maxOccurs="1">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:pattern value="(\.|[\.]{0,2}/[a-zA-Z0-9_\-/\.]+)$"></xs:pattern>
                    </xs:restriction>
                </xs:simpleType>
                <xs:annotation>
                    <xs:documentation>
                        Database location. A valid location can be either relative or
                        static e.g ../../db.sqlite, ./db.sqlite, /root/db.sqlite.
                    </xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:sequence>
        <xs:attribute name="enabled" type="xs:boolean" use="required" />
    </xs:complexType>
    <xs:annotation>
        <xs:documentation>
            Discovers tests by reading a SQLite database. These tests 
            can be filtered by configuring the filter XML or
            the database can be tailored before the test execution.
        </xs:documentation>
    </xs:annotation>
  </xs:element>
  <xs:element name="SourceLocation">
    <xs:complexType>
        <xs:sequence>
            <xs:element maxOccurs="1" minOccurs="1" ref="discovery:testRoot"/>
            <xs:element maxOccurs="1" minOccurs="0" ref="discovery:testPath"/>
        </xs:sequence>
    </xs:complexType>
    <xs:annotation>
        <xs:documentation>
            Test suite source code located. The source location is broken up 
            into two pieces to provide the facility of selecting a certain 
            folder within a test suite to discover tests within (basic filter).
        </xs:documentation>
    </xs:annotation>
  </xs:element>
  <xs:element name="testRoot">
    <xs:simpleType>
        <xs:restriction base="xs:string">
            <xs:pattern value="(\.|[\.]{0,2}/[a-zA-Z0-9_\-/\.]+[^/]{1})$"></xs:pattern>
        </xs:restriction>
    </xs:simpleType>
    <xs:annotation>
        <xs:documentation>
            Location where the fully test suite
            (utils, configuration files, etc) is located.
            Value can be a relative or static path
            e.g ../tests, ./tests, /root/tests
        </xs:documentation>
    </xs:annotation>
  </xs:element>
  <xs:element name="testPath">
    <xs:simpleType>
        <xs:restriction base="xs:string">
            <xs:pattern value="([a-zA-Z0-9]{1}[a-zA-Z0-9_\-/\.]*)?"></xs:pattern>
        </xs:restriction>
    </xs:simpleType>
    <xs:annotation>
        <xs:documentation>
            Folder located within the testRoot. This can be used to filter
            a subset of tests.
        </xs:documentation>
    </xs:annotation>
  </xs:element>
</xs:schema>

=== smokedice/YATES/config/discovery.xml
<discovery
    xmlns="discovery"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="discovery validation/discovery.xsd">
    <PythonNose enabled="true">
        <DiscoveryWorker enabled="true" />
        <DatabaseReader enabled="false">
            <location>./master.sqlite3</location>
        </DatabaseReader>
        <SourceLocation>
            <testRoot>/home/smoky/Documents/Workspace/TASv3/Code/tests/HWIntegration/tests/quickTests/tests</testRoot>
            <testPath>oem_tests</testPath>
        </SourceLocation>
    </PythonNose>
</discovery>
